server:
  port: 8099
  servlet:
    context-path: /demo


spring:
  application:
    name: security
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
    url: jdbc:mysql://localhost:3306/youle-user?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
mybatis-plus:
  mapper-locations: 'classpath*:/mapper/**/*.xml'
  #type-aliases-package: com.example.demo.pojo



